project: 
  type: website
  output-dir: docs
  resources:
    - figures

website:
  title: "Reproducibility with Git and Quarto"
  favicon: figures/socialImage.png
  sidebar:
    style: "docked"
    left:
      - text: Home
        href: index.qmd
    contents:
      - section: "Part Two - Quarto"
        href: quarto_overview.qmd
        contents:
          - episode_21_introduction.qmd
          - episode_22_gettingStarted.qmd
          - episode_23_codeBlocks.qmd
          - episode_24_projects.qmd
          - episode_25_researchPortfolio.qmd
          - episode_26_whereToNow.qmd
    tools:
      - icon: github
        href: https://github.com/GenomicsAotearoa/reproducibility_with_git_and_quarto


format:
  html:
    page-layout: full
    theme: zephyr
    css: styles.css
    navigation: true

