project: 
  type: website
  output-dir: docs
  resources:
    - figures

website:
  title: "Reproducibility with Git and Quarto"
  favicon: figures/socialImage.png
  sidebar:
    style: "docked"
    contents:
      - section: "Part One - Git"
        href: git_overview.qmd
        contents:
          - episode_01_AutomatedVersionControl.qmd
      - section: "Part Two - Quarto"
        href: quarto_overview.qmd
        contents:
          - episode_21_introduction.qmd
          - episode_22_gettingStarted.qmd
          - episode_23_codeBlocks.qmd
          - episode_24_projects.qmd
          - episode_25_researchPortfolio.qmd
          - episode_26_whereToNow.qmd



format:
  html:
    page-layout: full
    css: styles.css
    navigation: true

