---
title: Initial notes
toc: true
---

Four day workshop block, probably split across two weeks. 

Day 1: Git/github

Day 2: Quarto

Day 3: Containers

Day 4: Nextflow (or more broadly, software managers)


## Overarching themes

Tidy data and project organisation

What if....you disappeared


Mik/Paul have a lecture assessment, involving taking a small dataset from the attendee's own lab, and assessing how it compares with the data practices covered. Option to split this workshop into part a (overview, examples, all the tools) and part b: an afternoon of putting this into practice in an unstructured way - attendees in breakout rooms ("quiet", "group work"), re-join main room when you want discussion.


Richar Littauer is writing a manuscript "10 simple rules for making your code last beyond your current job". 


## Git/Github

Murray has expressed interest in collaborating on this, and has loose plans in place for a git/github workshop. He will handle git/github, and I'll build a quarto workshop, and the two will run back-to-back 28/29.05.25


## Quarto

Will involve exercise that will be continued throughout the day where we build up a website. Starting from very basic, single pdf about me/CV/cover page, which we upgrade to a multi-section website with embedded images and code. This website will be an 'about me', which will then be pinned as a repo, for the purpose of self-advertising/so that github can be used as a link in your physical CV. 

- Need to have a good example of what this might look like for other people (i.e., I need to create an example of my own).

Quarto has an inherent tie to the world of Open Access and the concept of the Public Garden (which is *scary*). 