---
title: Story Repo
subtitle: An About Me Page
toc: true
---

"Elevator pitch", "About Me" page, "Your Story". These are some of the terms you might hear to describe a presentation (either spoken or in document form) that you use to promote yourself and your career. This might be a cold call/email while you are job hunting or something you do while meeting people at a conference to make a connection and an impression. If you make it past that first stage and do make an impression, for anyone working in the field of bioinformatics you can expect prospective employers to ask for a link to your github. Having a set of tidy repos that document your workflow is the minimum you should aim for. 

For the rest of this workshop we will take the time to create something to support those repos: a dedicated repo that provides an overview of your career skills and highlights. To get a better understanding of why I am recommending this and what we are trying to do, I recommend this talk from posit::conf(2024) titled "[Github - How to tell your professional story](https://www.youtube.com/watch?v=R-bPjavai5A&list=PL9HYL-VRX0oSFkdF4fJeY63eGDvgofcbn&index=20)". In this talk, Dr. Abigail Haddad outlines how Github can be used to demonstrate not just the raw coding skills you use frequently, but also the auxilliary skills that define how you work - your problem solving skills, your practices, and how you communicate. 

We are going to take some of the advice from that talk, which says that all of your github should be used to *actively* demonstrate your skills and tell your story, and we are going to compress it down to a single github repo which will convey (or at least introduce) your story. We will Pin this repo so that it's the first thing people see when they visit your github page, and publish it as a working website so that you also have a link you can drop into LinkedIn or Bluesky posts, incorporate into your email signatures, whenever you feel it's appropriate to do some self-marketing. 