---
title: Part two - Quarto
toc: true
---

## What will we do today with Quarto?

 **Key Objectives and Learning Outcomes** ✨

- Understand about the purpose of Quarto and how it improves reproducibility
- Learn basic syntax of the Quarto markdown language, such as formatting headings, lists, bold and italics  
- Showcase how to render Quarto documents as html, slideshow, pdf 
- Learn how to link multiple Quarto documents as a Quarto "Project" and render as a website
- Explore different ways to customise theming, styles, output formatting etc.
- Publish a website with GitHub pages.



## Setup on local machine

Quarto comes as a part of RStudio, so if you already have [RStudio](git_overview.qmd#setup-on-local-machine) installed **you don't need to do anything extra for this part of the workshop.** 

However, there are lots of ways you can use and integrate Quarto into your preferred tool:  

* See ["Get Started" in Quarto docs](https://quarto.org/docs/get-started/) to install the Quarto command line interface and links to download other compatible tools. 
